name: Hello world

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Build Phase
        run: echo "Hello This is Build Phase"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello to Test Phase
        run: echo "Hello This is Test Phase"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Deploy Phase
        run: echo "Hello This is Deploy Phase
    
